// <auto-generated />
namespace CamelDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _201406301652_add_ProductType_Price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201406301652_add_ProductType_Price));
        
        string IMigrationMetadata.Id
        {
            get { return "201406300853117_201406301652_add_ProductType_Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
