// <auto-generated />
namespace CamelDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class update_QualitylossPercent_precision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_QualitylossPercent_precision));
        
        string IMigrationMetadata.Id
        {
            get { return "201409220258529_update_QualitylossPercent_precision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
