// <auto-generated />
namespace CamelDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _201406251345_add_QualityLoss_QualityLossPercent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201406251345_add_QualityLoss_QualityLossPercent));
        
        string IMigrationMetadata.Id
        {
            get { return "201406250546142_201406251345_add_QualityLoss_QualityLossPercent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
